#!/usr/bin/perl
use strict;
use warnings;
use JSON;
use NethServer::ApiTools;
use LWP::Simple qw (head);
my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};
my $ret = {};
my $url = 'http://mrmarkuz.dynu.net/mirror/mrmarkuz/';
my $head = `/usr/bin/curl -I $url --connect-timeout 2 --max-time 5`;
if ( $cmd eq "app-info") {
    if ($head =~ 'HTTP/1.1 200 OK') {
            $ret = {
                'name' => "mrmarkuz repo is online",
                'url' => "https://mrmarkuz.dynu.net/mirror/mrmarkuz/7/repoview/",
                'description' => "Provides mrmarkuz repo, open link to get repoview",
                'summary' => "Provides mrmarkuz repo, open link to get repoview"
            };
        }
        else {
            $ret = {
                'name' => "mrmarkuz repo is offline",
                'url' => "https://www.markusneuberger.at",
                'description' => "mrmarkuz repo seems to be offline",
                'summary' => "mrmarkuz repo seems to be offline"
            };
        }
} else {
    NethServer::ApiTools::error();
}
print encode_json($ret);
